title: Naman Doshi
email: namanjd@outlook.com
author: Naman Doshi
description: I like to build stuff on the web

baseurl: ""
url: "https://www.gofornaman.github.io"

google_analytics: UA-112766650-2

date_format: "%B %Y"
permalink: /writing/:title

markdown: kramdown

sass:
  style: compressed

include:
  - _pages

keep_files:
  - assets/build

exclude:
  - assets/js
  - notebooks/nb
  - notebooks/tpl
  - notebooks/venv
  - node_modules
  - NOTES
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - webpack.config.js
